---
- hosts: default 
  vars:
    username: vagrant
    home: "/home/{{ username }}"
    src_home: "{{ home }}/repos"
  user: "{{ username }}"
  tasks:
    - name: "create folders"
      file: 
        path: "{{ item }}" 
        state: directory
      with_items:
        - "{{ src_home }}"
    - name: update apt-get for sublime
      shell: 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
    - name: add extra apt-get repositories 
      apt_repository:
        repo: "{{ item }}"
      become: true
      become_user: root
      with_items:
        - 'ppa:fish-shell/release-2'
        - 'ppa:openjdk-r/ppa'
    - name: Install libraries with apt
      apt: 
        name: "{{ item }}"
        update_cache: yes
        allow_unauthenticated: yes
      become: true
      become_user: root
      with_items:
        - maven
        - default-jdk 
        - git
        - libcurl4-openssl-dev
        - libexpat1-dev
        - tcl-dev
        - gettext
        - libssl-dev
        - sublime-text
        - fish
        - openjdk-7-jdk
        - silversearcher-ag
        - vim
        - vagrant
        - virtualbox
        - python-pip
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce
    - name: Add dockers GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      become: true
      become_user: root
    - name: setup stable repository for docker
      shell: "add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'"
      become: true
      become_user: root
    - name: clone git
      git: 
        dest: "{{ src_home }}/git"
        repo: https://github.com/git/git.git
        version: v2.14.2
    - name: install latest version
      shell: make; make install
      args:
        chdir: "{{ src_home }}/git"
    - name: download intellij
      unarchive:
        src: https://download.jetbrains.com/idea/ideaIC-2017.2.5.tar.gz # extract version to a variable?
        dest: /opt
        remote_src: yes
      become: true
      become_user: root
