---
- hosts: localhost
  connection: local
  vars:
    username: vagrant
    group: "{{ usergroup }}"
    home: "/home/{{ username }}"
    src_home: "{{ home }}/repos"
    git_version: "v2.36.1"
  user: "{{ username }}"
  tasks:
    - name: "create folders"
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ group }}"
      with_items:
        - "{{ src_home }}"
    - name: add extra apt-get repositories
      apt_repository:
        repo: "{{ item }}"
      become: true
      become_user: root
      with_items:
        - 'ppa:fish-shell/release-3'
        - 'ppa:linuxuprising/java'
    - name: Add dockers GPG key
      shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
      become: true
      become_user: root
    - name: setup stable repository for docker
      shell: "add-apt-repository 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'"
      become: true
      become_user: root
    - name: Add Microsoft Visual Studio Code GPG key
      shell: "curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg"
      become: true
      become_user: root
    - name: setup stable repository for code
      shell: "add-apt-repository 'deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main'"
      become: true
      become_user: root
    - name: auto accept oracle license for java
      shell: "echo debconf shared/accepted-oracle-license-v1-3 select true | debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-3 seen true | debconf-set-selections"
      become: true
      become_user: root
    - name: Install libraries with apt
      apt:
        name: "{{ item }}"
        update_cache: yes
        allow_unauthenticated: yes
      become: true
      become_user: root
      with_items:
        - maven
        - default-jdk
        - git
        - libcurl4-openssl-dev
        - libexpat1-dev
        - tcl-dev
        - gettext
        - libssl-dev
        - fish
        - silversearcher-ag
        - vim
        - vagrant
        - virtualbox
        - python3-pip
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-compose
        - tree
        - apt-transport-https
        - code
        - parcellite
        - openjdk-8-jdk
        - npm
        - openjdk-11-jdk
        - vagrant
        - oracle-java17-installer
        - snapd
    - name: Install Jetbrains software
      shell: snap install {{ item }} --classic
      become: true
      become_user: root
      with_items:
        - pycharm-community
        - intellij-idea-community
        - atom
        - spotify
    - name: clone git
      git:
        dest: "{{ src_home }}/git"
        repo: https://github.com/git/git.git
        version: "{{ git_version }}"
    - name: install latest version
      shell: make; make install
      args:
        chdir: "{{ src_home }}/git"
    - name: install kubectl
      shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      args:
        chdir: /usr/local/bin/
      become: true
      become_user: root
    - name: install helm
      shell: 'curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get > get_helm.sh && chmod 700 get_helm.sh && ./get_helm.sh'
      become: true
      become_user: root
    - name: install npm packages
      shell: 'npm install -g tldr'
      become: true
      become_user: root
